name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm ci

      - name: Archive production artifacts
        run: zip -r release.zip . -x '*.git*'
        working-directory: ${{ github.workspace }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-poc-service
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/release.zip
